name: Run Python Script on Folder Commit

on:
  push:
    paths:
      - 'bdd_scenarios/**'
    branches:
      - main

jobs:
  generate-groovy-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Get files changed in last commit
      uses: tj-actions/changed-files@v45
      id: changed-files

    - name: Generate groovy files from BDD scenarios
      run: |
        ALL_CHANGED_FILES="${{ steps.changed-files.outputs.all_changed_files }}"

        for file in $ALL_CHANGED_FILES; do
          if [[ "$file" =~ bdd_scenarios/.*\.feature$ ]]; then
            python -m behave --no-capture "$file"
          fi
        done

    - name: Push generated groovy scenarios to repository
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add scenarios

        git commit -m "Add new scenarios"
        git push origin HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
