name: 🆕 Create JSON and groovy scenarios for RC testing

on:
  workflow_dispatch:
    inputs:
      scenario_data:
        description: 'JSON representation of RC testing scenario'
        required: true

env:
  SCENARIO_DATE: ${{ fromJson(github.event.inputs.scenario_data).date}}
  SCENARIO_DATA: '${{ github.event.inputs.scenario_data }}'

jobs:
  create-scenario:
    runs-on: ubuntu-latest

    concurrency:
      group: "crud_rc_scenarios"
      cancel-in-progress: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements_prod.txt

    - name: Save JSON scenario
      run: |
        echo $SCENARIO_DATA > json_scenarios/$SCENARIO_DATE.json

    - name: Generate groovy file from scenario representation in JSON format
      run: |
        python generate_groovy_scenario.py --json_scenario_path=json_scenarios/$SCENARIO_DATE.json

    - name: Push changes to repository
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

        git add json_scenarios scenarios
        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Create scenario for $SCENARIO_DATE"
          git push origin HEAD:main
        fi
        
        sleep 3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
