name: 🗑 Delete JSON and groovy scenarios for RC testing

on:
  workflow_dispatch:
    inputs:
      scenario_date:
        description: 'Date for scenario to be deleted. Unique identifier of scenario'
        required: true

env:
  SCENARIO_ID: ${{ github.event.inputs.scenario_date }}

jobs:
  delete-scenario:
    runs-on: ubuntu-latest

    concurrency:
      group: "rc-delete"
      cancel-in-progress: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements_prod.txt

    - name: Delete JSON and groovy scenarios for $SCENARIO_ID"
      run: |
        rm json_scenarios/$SCENARIO_ID.json scenarios/$SCENARIO_ID.groovy

    - name: Push changes to repository
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

        git add json_scenarios scenarios
        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Delete scenario for $SCENARIO_ID"
          git push origin HEAD:main
        fi

        sleep 3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
