name: Groovy file generation based on JSON representation of RC scenario

on:
  workflow_dispatch:
    inputs:
      scenario_data:
        description: 'JSON representation of RC testing scenario'
        required: true

jobs:
  generate-groovy-file:
    runs-on: ubuntu-latest

    concurrency:
      group: "groovy_generation_on_push"
      cancel-in-progress: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements_prod.txt

    - name: Generate groovy file from scenario representation in JSON format
      run: |
        python generate_scenario.py --json_scenario="${{ github.event.inputs.scenario_data }}"

    - name: Push generated groovy scenarios to repository
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

        git add scenarios
        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Generate groovy file for ${{ fromJson(github.event.inputs.scenario_data).date"
          git push origin HEAD:main
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
