name: Generate groovy files based on JSON representation of RC scenarios

on:
  push:
    paths:
      - 'json_scenarios/**'
    branches:
      - main

jobs:
  generate-groovy-file:
    runs-on: ubuntu-latest

    concurrency:
      group: "groovy_generation_on_push"
      cancel-in-progress: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Get files changed in last commit
      uses: tj-actions/changed-files@v45
      id: changed-files

    - name: Generate groovy files from scenario representation in JSON format
      run: |
        ALL_CHANGED_FILES="${{ steps.changed-files.outputs.all_changed_files }}"
        if [[ -z "$ALL_CHANGED_FILES" ]]; then
          echo "No changed files"
          exit 0
        fi

        for file in $ALL_CHANGED_FILES; do
          if [[ "$file" =~ json_scenarios/.*\.json && -f "$file" ]]; then
            python src/generate_scenario.py --json_scenario_path="$file" 
          fi
        done

    - name: Push generated groovy scenarios to repository
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

        git add scenarios
        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m "${{ github.event.head_commit.message }}"
          git push origin HEAD:main
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
