name: Check Pending or Queued Workflows

on:
  workflow_dispatch:

jobs:
  check-pending-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for pending or queued workflows using curl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          API_URL="https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs"
          RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "$API_URL")
          PENDING_WORKFLOWS=$(echo "$RESPONSE" | jq '.workflow_runs | map(select(.status == "queued" or .status == "pending"))')

          if [ "$(echo "$PENDING_WORKFLOWS" | jq 'length')" -gt 1 ]; then
            echo "Found pending or queued workflows:"
            echo "$PENDING_WORKFLOWS" | jq -r '.[] | "- \(.name) (ID: \(.id), Status: \(.status))"'
          sleep 5
          else
            echo "No pending or queued workflows."
          fi
